// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID      `json:"id"`
	ExternalID string         `json:"external_id"`
	Email      string         `json:"email"`
	Username   string         `json:"username"`
	TenantID   sql.NullString `json:"tenant_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
}
