// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    external_id, email, username, tenant_id, first_name, last_name
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, external_id, email, username, tenant_id, created_at, updated_at, first_name, last_name
`

type CreateUserParams struct {
	ExternalID string         `json:"external_id"`
	Email      string         `json:"email"`
	Username   string         `json:"username"`
	TenantID   sql.NullString `json:"tenant_id"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ExternalID,
		arg.Email,
		arg.Username,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Username,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, email, username, tenant_id, created_at, updated_at, first_name, last_name FROM users
WHERE external_id = $1 LIMIT 1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Username,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, email, username, tenant_id, created_at, updated_at, first_name, last_name FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Username,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    email = $2,
    username = $3,
    tenant_id = $4,
    first_name = $5,
    last_name = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, email, username, tenant_id, created_at, updated_at, first_name, last_name
`

type UpdateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Username  string         `json:"username"`
	TenantID  sql.NullString `json:"tenant_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.Username,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
